public enum EntityField
{
    Idle,
    Resting,
    GoingToFood,
    GoingToWater,
    Eating,
    Drinking,
    SearchingForMate,
    Reproducing,
    FoodClose,
    FoodFar,
    WaterClose,
    WaterFar,
    RabbitClose,
    RabbitFar,
    Fertile,
    NotFertile,
    Hungry,
    NotHungry
}