public enum EntityField
{
    FoodClose,
    FoodFar,
    FoodPresenceHigh,
    FoodPresenceLow,
    WaterClose,
    WaterFar,
    WaterPresenceHigh,
    WaterPresenceLow,
    MateClose,
    MateFar,
    MatePresenceHigh,
    MatePresenceLow,
    FoeClose,
    FoeFar,
    FoePresenceHigh,
    FoePresenceLow,

    //Actions
    Idle,
    Resting,
    GoingToFood,
    GoingToWater,
    Eating,
    Drinking,
    SearchingForMate,
    Reproducing
}