public enum EntityInput
{
    FoodClose = EntityField.FoodClose,
    FoodFar = EntityField.FoodFar,
    FoodPresenceHigh = EntityField.FoodPresenceHigh,
    FoodPresenceLow = EntityField.FoodPresenceLow,
    WaterClose = EntityField.WaterClose,
    WaterFar = EntityField.WaterFar,
    WaterPresenceHigh = EntityField.WaterPresenceHigh,
    WaterPresenceLow = EntityField.WaterPresenceLow,
    MateClose = EntityField.MateClose,
    MateFar = EntityField.MateFar,
    MatePresenceHigh = EntityField.MatePresenceHigh,
    MatePresenceLow = EntityField.MatePresenceLow,
    FoeClose = EntityField.FoeClose,
    FoeFar = EntityField.FoeFar,
    Fertile = EntityField.Fertile,
    NotFertile = EntityField.NotFertile,
    Hungry = EntityField.Hungry,
    NotHungry = EntityField.NotHungry,
    FoePresenceHigh = EntityField.FoePresenceHigh,
    FoePresenceLow = EntityField.FoePresenceLow,
    Thirsty = EntityField.Thirsty,
    NotThirsty = EntityField.NotThirsty
}